# Site settings
title: Vince Carpentier
twitter_username: vrc86
name: Vince Carpentier

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/vrcarpentier
 - title: LinkedIn
   url: www.linkedin.com/in/vincent-carpentier-24778739

#Any buzzword skills you want to include
skills:
 - JavaScript
 - ColdFusion
 - CSS
 - HTML
 - SQL
 - Python

#Work experience is required
roles:
 - title: Specialist-System Engineer
   start: Feb 2018
   end: Ongoing
   employer: AT&T
   description: Web developer.
 - title: Sr. Specialist-Network Support
   start: Sep 2018
   end: Feb 2018
   employer: AT&T
   description: Web developer.
 - title: Specialist-Network Support
   start: May 2014
   end: Sep 2016
   employer: AT&T
   description: Incident Manager, Mobility - Global Technology Operations Center. </br> As a member of the GTOC Mobility Console, I managed the response and recovery actions during customer impacting network outages. When an outage occurs GTOC Mobility Incident Managers correlate network events among other AT&T organizations, engage the appropriate resources and teams in order to restore service, and prepare incident summary reports.
 - title: Specialist-Network Support
   start: Sep 2012
   end: May 2014
   employer: AT&T
   description: As a member of the GNOC Communications Console, I monitored Twitter, Facebook, blogs and any other social media outlets for any issues concerning AT&T’s network, services or customers. In addition, the GNCC works with other network teams to provide information concerning the customer experience and relate customer issues to network incidents. GNCC Managers proactively monitor the external environment for any conditions that could cause an incident in the AT&T Network. If necessary, GNCC Managers will distribute the appropriate notifications regarding these conditions to help network teams prepare for possible service impact. This valuable communication process helps minimize service impact and ensure a speedy resolution. 
 - title: Retail Sales Consultant
   start: Aug 2009
   end: Sep 2012
   employer: AT&T
   description: Sales and customer service.

#Education is required
education:
 - level: Bachelor of Arts
   date: 2015
   subject: Political Science 
   school: Penn State World Campus

#This section is optional (as is the image link below)
Udacity:
   courses:
    - title: Intro to Programming Nanodegree
      link: https://www.udacity.com/course/intro-to-programming-nanodegree--nd000
      date: September 2016
    - title: Front-End Web Developer Nanodegree
      link: https://www.udacity.com/course/front-end-web-developer-nanodegree--nd001
      date: Feb 2017
    - title: Full Stack Web Developer Nanodegree
      link: https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd004
      date: June 2018

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
 Hi
